# =========================
# APPLICATION
# =========================
spring.application.name=demo-project
server.port=8080


# =========================
# DATASOURCE (MySQL)
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/demo_project
spring.datasource.username=bsharan
spring.datasource.password=@GH72DBUW^@@&#NSsajzJI#$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
#
spring.jpa.hibernate.ddl-auto=update

# values gets overridden
order.type=online
#order.type=offline
#order.type=online

# configure if the dispatcher servlet starts before or after the first URL is hit
# spring.mvc.servlet.load-on-startup = 1

spring.security.user.name=user
spring.security.user.password=password
spring.security.user.roles=USER,ADMIN
# when these values are present we see below log line - main] r$InitializeUserDetailsManagerConfigurer : Global AuthenticationManager configured with UserDetailsService bean with name inMemoryUserDetailsManager

# logging
# spring security
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web.FilterChainProxy=TRACE
logging.level.org.springframework.security.web.authentication=TRACE
logging.level.org.springframework.security.authorization=TRACE