# =========================
# APPLICATION
# =========================
spring.application.name=demo-project
server.port=8080


# =========================
# DATASOURCE (MySQL)
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/demo_project
spring.datasource.username=bsharan
spring.datasource.password=@GH72DBUW^@@&#NSsajzJI#$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

spring.jpa.hibernate.ddl-auto=update

# values gets overridden
order.type=online
#order.type=offline
#order.type=online